Update Install

diff --git a/cutadapt/Install b/cutadapt/Install
--- a/cutadapt/Install
+++ b/cutadapt/Install
@@ -3,118 +3,64 @@
 # Organization: MDIBL
 # Author: Lucie Hutchins
 # Date: January 2018
-# Source : http://hannonlab.cshl.edu/fastx_toolkit/install_centos.txt
-## Script to build and install a new package
-
+# Modified: February 2018
+#
+# This script is called by the main install script 
+# (install_package.sh)  to build and install 
+# a new version of the package 
+#
+# What it does:
+# 1) source the main config file to set global path
+# 2) untar the downloaded tar file
+# 3) builds and install the package
+#
+# Note: the following environment variables are expected to be set
+# by the caller
+# 1) GLOBAL_CONFIG
+# 2) PACKAGE_BASE
+# 3) PACKAGE_DEPENDS
+#
 cd `dirname $0`
-
 SCRIPT_NAME=`basename $0`
 WORKING_DIR=`pwd`
-##These config files are relative to
-# the Install script working directory
-dependents_file=dependencies.cfg
-pack_config_file=cutadapt_repos.cfg
-
-if [ ! -f $dependents_file ]
+echo "==" 
+echo "Server Name: `uname -n`" 
+echo "Install Date: `date`" 
+if [ ! -f ../${GLOBAL_CONFIG} ]
 then
-   echo "The dependencies file: $dependents_file is missing"
-   echo " From $WORKING_DIR"
+  echo "'../${GLOBAL_CONFIG}' file missing "     
+  exit 1
+fi
+source ./../${GLOBAL_CONFIG}
+if [ "${PACKAGE_DEPENDS}" = "" ]
+then
+   echo "ERROR: PACKAGE_DEPENDS not set"
    exit 1
 fi
-if [ ! -f ../Configuration ]
+PACKAGE_DEPENDENCIES_FILE=`basename ${PACKAGE_DEPENDS}`
+source ./${PACKAGE_DEPENDENCIES_FILE}
+if [ ! -d ${PACKAGE_BASE} ]
 then
-  echo "'../Configuration' file missing "     
-  exit 1
-fi
-if [ ! -f $1 ]
-then
-  echo "'$1' file missing"     
-  exit 1
-fi
-
-source ./../Configuration
-echo ""
-source ./$dependents_file
-source ./$pack_config_file
-
-if [ ! -f $RELEASE_FILE ]
-then
-   echo "File $RELEASE_FILE does not exists"
+   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
    exit 1
-fi
-
-RELEASE_NUMBER=`cat $RELEASE_FILE`
-LOG_FILE="${DOWNLOADS_LOG_DIR}/$SCRIPT_NAME.$SHORT_NAME.$RELEASE_NUMBER.log"
-PACKAGE_BASE=$LOCAL_DIR/$RELEASE_DIR
-
-rm -rf $LOG_FILE
-touch $LOG_FILE
-
-rstatus=""
-echo "==" | tee -a $LOG_FILE
-echo "Product: $GIT_REPOS" | tee -a $LOG_FILE
-echo "Install directory: $PACKAGE_BASE" | tee -a $LOG_FILE
-echo "Release version: $RELEASE_NUMBER" | tee -a $LOG_FILE
-echo "Install on Server Name: `uname -n`" | tee -a $LOG_FILE
-echo "==" | tee -a $LOG_FILE
-
-echo "Running the dependency test" | tee -a $LOG_FILE
-echo "Missing dependencies:" | tee -a $LOG_FILE
-for dependency in $DEPENDENCIES
-do
-    token=`which $dependency`
-    if [ ! -f "$token" ]
-    then
-       echo "Dependency: $dependency" | tee -a $LOG_FILE
-       rstatus="Failed"
-    fi
-done
-# Check Lib dependency
-for dependency in $LIB_DEPENDENCIES
-do
-  tokens=`locate $dependency`
-  for lib_path in $tokens
-  do
-    if [ ! -f $lib_path ]
-    then
-      echo "Dependency: $dependency" | tee -a $LOG_FILE
-      rstatus="Failed"
-    fi
-  done
-done
-echo "==" | tee -a $LOG_FILE
-if [ "$rstatus" == Failed ]
-then
-  echo "Dependency test Failed" | tee -a $LOG_FILE
-  exit 1
-fi
-echo "Dependency test passed" | tee -a $LOG_FILE
-echo "Checking the Install directory:" | tee -a $LOG_FILE
-# Execute the Install command for this package
-#
-if [ ! -d $PACKAGE_BASE ]
-then
-  echo "ERROR:$PACKAGE_BASE directory missing" | tee -a $LOG_FILE    
-  echo "Status: FAILED" | tee -a $LOG_FILE
-  exit 1
 fi
 version=`echo $RELEASE_NUMBER | sed -e 's/^v//' | sed -e 's/^[[:space:]]*//'`
 echo "$version"
 #Shared installation (on a cluster)
-virtualenv $PACKAGE_BASE/venv
+${VIRTUALENV} $PACKAGE_BASE/venv
 if [ $? -ne 0 ]
 then
-  echo "ERROR:'virtualenv $PACKAGE_BASE/venv' failed"
-  echo "Status: FAILED"| tee -a $LOG_FILE
+  echo "ERROR:'virtualenv ${PACKAGE_BASE}/venv' failed"
+  echo "Status: FAILED"
   exit 1
 fi
-echo "Running 'sudo $PACKAGE_BASE/venv/bin/pip install --install-option="--install-scripts=$SOFTWARE_BASE/bin" cutadapt==$version' from `pwd`" | tee -a $LOG_FILE
-sudo $PACKAGE_BASE/venv/bin/pip install --install-option="--install-scripts=$SOFTWARE_BASE/bin" cutadapt==$version
+echo "Running 'sudo ${PACKAGE_BASE}/venv/bin/pip install --install-option="--install-scripts=${SOFTWARE_BIN_BASE}"
+cutadapt==$version' from `pwd`" 
+sudo ${PACKAGE_BASE}/venv/bin/pip install --install-option="--install-scripts=${SOFTWARE_BIN_BASE}" cutadapt==$version
 #sudo pip install --upgrade cutadapt
 if [ $? -ne 0 ]
 then
-  echo "ERROR:'sudo $PACKAGE_BASE/venv/bin/pip install --install-option="--install-scripts=$SOFTWARE_BASE/bin" cutadapt==$version' failed"
-  echo "Status: FAILED"| tee -a $LOG_FILE
+  echo "Status: FAILED"
   exit 1
 fi
 echo "Status: SUCCESS"
