Update Install

diff --git a/toil/Install b/toil/Install
--- a/toil/Install
+++ b/toil/Install
@@ -2,93 +2,82 @@
 
 # Organization: MDIBL
 # Author: Lucie Hutchins
-# Date: November 2017
-## Script to build and install a new package
-#http://toil.readthedocs.io/en/3.11.0/gettingStarted/install.html
-
+# MODIFIED: March 2018
+#
+# This script is called by the main install script 
+# (install_package.sh)  to build and install 
+# a new version of the package 
+#
+# What it does:
+# 1) source the main config file to set gloabl path
+# 2) source the dependencies config file
+# 3) source package config file
+# 3) build and install package
+#
+# Note: the following environment variables are expected to be set
+# by the caller
+# 1) GLOBAL_CONFIG
+# 2) PACKAGE_DEPENDS
+# 3) PACKAGE_CONFIG_FILE
+#
 cd `dirname $0`
-
 SCRIPT_NAME=`basename $0`
 WORKING_DIR=`pwd`
-##These config files are relative to
-# the Install script working directory
-dependents_file=dependencies.cfg
-pack_config_file=toil_repos.cfg
 
-if [ ! -f $dependents_file ]
+echo "==" 
+echo "Server Name: `uname -n`" 
+echo "Install Date: `date`" 
+if [ ! -f ../${GLOBAL_CONFIG} ]
 then
-   echo "The dependencies file: $dependents_file is missing"
-   echo " From $WORKING_DIR"
-   exit 1
-fi
-if [ ! -f ../Configuration ]
-then
-  echo "'../Configuration' file missing "     
+  echo "'../${GLOBAL_CONFIG}' file missing "     
   exit 1
 fi
-if [ ! -f $1 ]
+source ./../${GLOBAL_CONFIG}
+if [ "${PACKAGE_DEPENDS}" = "" ]
 then
-  echo "'$1' file missing"     
-  exit 1
-fi
-
-source ./../Configuration
-source ./$dependents_file
-source ./$pack_config_file
-
-if [ ! -f ${RELEASE_FILE} ]
-then
-   echo "File ${RELEASE_FILE} does not exists"
+   echo "ERROR: PACKAGE_DEPENDS not set"
    exit 1
 fi
+PACKAGE_DEPENDENCIES_FILE=`basename ${PACKAGE_DEPENDS}`
+source ./${PACKAGE_DEPENDENCIES_FILE}
+toil_config=`basename ${PACKAGE_CONFIG_FILE}`
 
-LOG_FILE="${DOWNLOADS_LOG_DIR}/$SCRIPT_NAME.$SHORT_NAME.log"
-
-rm -rf $LOG_FILE
-touch $LOG_FILE
-
-rstatus=""
-echo "==" | tee -a $LOG_FILE
-echo "Product: $GIT_REPOS" | tee -a $LOG_FILE
-echo "Install directory: $TOIL_BASE" | tee -a $LOG_FILE
-echo "Install on Server Name: `uname -n`" | tee -a $LOG_FILE
-echo "==" | tee -a $LOG_FILE
+if [ ! -f ${toil_config} ]
+then
+  echo "'${toil_config}' file missing under `pwd` "     
+  exit 1
+fi
+source ./${toil_config}
 
 #Create virtualenv directory for this repos as needed
-mkdir -p $TOIL_BASE
-virtualenv -p $PYTHON $TOIL_BASE
+if [ ! -d ${TOIL_BASE} ]
+then
+    mkdir -p ${TOIL_BASE}
+    ${VIRTUALENV} -p ${PYTHON} ${TOIL_BASE}
+fi
 #
 # activate virtualenv
-#
 source $TOIL_BASE/bin/activate
 
-pip install toil 2>&1 | tee -a $LOG_FILE
-pip install toil cwl 2>&1 | tee -a $LOG_FILE
+${PIP} install toil 2>&1 
+${PIP} install toil cwl 2>&1 
 
 #Check the install
 rstatus="SUCCESS"
-for bin_file in $FILE_CHECK
+for bin_file in ${FILE_CHECK}
 do
-    if [ ! -f $TOIL_BASE/bin/$bin_file ]
+    if [ ! -f ${TOIL_BASE}/bin/${bin_file} ]
     then
-       echo "$TOIL_BASE/bin/$bin_file missing" | tee -a $LOG_FILE
+       echo "${TOIL_BASE}/bin/${bin_file} missing"
        rstatus="FAILED"
      fi
 done
 
 if [ "$rstatus" == FAILED ]
 then
-   echo "$rstatus" | tee -a $LOG_FILE
+   echo "$rstatus" 
    exit 1
 fi
-#get the version we just installed
-RELEASE_NUMBER=`toil --version`
-rm -f $RELEASE_FILE
-touch $RELEASE_FILE
-echo "releases/$RELEASE_NUMBER" > $RELEASE_FILE
-echo "Release version: $RELEASE_NUMBER" | tee -a $LOG_FILE
-echo $rstatus | tee -a $LOG_FILE
-#
 #exit virtualenv
 #
 deactivate
