Added the --with-bam option

diff --git a/cufflinks/Install b/cufflinks/Install
--- a/cufflinks/Install
+++ b/cufflinks/Install
@@ -100,7 +100,17 @@ then
 fi
 
 cd $PACKAGE_BASE
-./configure --prefix=$SOFTWARE_BASE --with-boost=$SOFTWARE_BASE --with-eigen=$SOFTWARE_BASE 
+if [ ! -f configure ]
+then
+   autoreconf --install
+fi
+if [ ! -f configure ]
+then
+   echo "Install Failed: Missing $PACKAGE_BASE/configure file"
+   exit 1 
+fi
+
+./configure --prefix=$SOFTWARE_BASE --with-boost=$SOFTWARE_BASE --with-eigen=$SOFTWARE_BASE --with-bam=$SOFTWARE_BASE 
 
 make  2>&1 | tee -a $LOG_FILE
 rstatus="SUCCESS"
