Update Install

diff --git a/blat/Install b/blat/Install
--- a/blat/Install
+++ b/blat/Install
@@ -38,7 +38,6 @@ then
    exit 1
 fi
 LOG_FILE="${DOWNLOADS_LOG_DIR}/${SCRIPT_NAME}.${SHORT_NAME}.${RELEASE_NUMBER}.log"
-
 rm -rf ${LOG_FILE}
 touch ${LOG_FILE}
 rstatus=""
@@ -48,18 +47,23 @@ echo "Install directory: ${PACKAGE_BASE}" | tee -a ${LOG_FILE}
 echo "Release version: ${RELEASE_NUMBER}" | tee -a ${LOG_FILE}
 echo "Install on Server Name: `uname -n`" | tee -a ${LOG_FILE}
 echo "==" | tee -a ${LOG_FILE}
-cd ${PACKAGE_BASE}/${RELEASE_DIR}
+depends=`basename ${PACKAGE_DEPENDS}`
+if [ ! -f ${depends} ]
+then
+   echo "ERROR: dependencies.cfg file missing"
+   exit 1
+fi
 #Copy the binaries to /opt/software/bin
 #
 for bin_file in ${FILE_CHECK}
 do
-    if [ ! -f ${bin_file} ]
+    if [ ! -f ${PACKAGE_BASE}/${RELEASE_DIR}/${bin_file} ]
     then
-        echo "${bin_file} missing"
+        echo "${bin_file} missing under ${PACKAGE_BASE}/${RELEASE_DIR}"
         rstatus="FAILED"
     else
-        chmod 755 ${bin_file}
-        cp -p  ${bin_file} ${SOFTWARE_BASE}/bin/
+        chmod 755 ${PACKAGE_BASE}/${RELEASE_DIR}/${bin_file}
+        cp -p  ${PACKAGE_BASE}/${RELEASE_DIR}/${bin_file} ${SOFTWARE_BASE}/bin/
     fi
 done
 echo "${rstatus}" 
