Update Install

diff --git a/boost/Install b/boost/Install
--- a/boost/Install
+++ b/boost/Install
@@ -10,107 +10,33 @@
 # 2) source the dependencies config file
 # 3) runs the build and copy  the executables to /opt/software/bin
 #
+#
 # Note: the following environment variables are expected to be set
-#       by the caller
+# by the caller
 # 1) GLOBAL_CONFIG
 # 2) PACKAGE_BASE
-
+#
 cd `dirname $0`
-
 SCRIPT_NAME=`basename $0`
 WORKING_DIR=`pwd`
-##These config files are relative to
-# the Install script working directory
-dependents_file=dependencies.cfg
-pack_config_file=boost_repos.cfg
-
-if [ ! -f $dependents_file ]
+echo "==" 
+echo "Server Name: `uname -n`" 
+echo "Install Date: `date`" 
+if [ ! -f ../${GLOBAL_CONFIG} ]
 then
-   echo "The dependencies file: $dependents_file is missing"
-   echo " From $WORKING_DIR"
-   exit 1
-fi
-if [ ! -f ../Configuration ]
-then
-  echo "'../Configuration' file missing "     
+  echo "'../${GLOBAL_CONFIG}' file missing "     
   exit 1
 fi
-if [ ! -f $1 ]
+source ./../${GLOBAL_CONFIG}
+if [ ! -d ${PACKAGE_BASE} ]
 then
-  echo "'$1' file missing"     
-  exit 1
-fi
-
-source ./../Configuration
-source ./$dependents_file
-source ./$pack_config_file
-
-if [ ! -f ${LOCAL_DIR}/current_release_NUMBER ]
-then
-   echo "File ${LOCAL_DIR}/current_release_NUMBER does not exists"
+   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
    exit 1
 fi
-
-RELEASE_NUMBER=`cat ${LOCAL_DIR}/current_release_NUMBER`
-LOG_FILE="${DOWNLOADS_LOG_DIR}/$SCRIPT_NAME.$SHORT_NAME.$RELEASE_NUMBER.log"
-PACKAGE_BASE=$LOCAL_DIR/$GIT_REPOS 
-
-rm -rf $LOG_FILE
-touch $LOG_FILE
-
-rstatus=""
-echo "==" | tee -a $LOG_FILE
-echo "Product: $GIT_REPOS" | tee -a $LOG_FILE
-echo "Install directory: $PACKAGE_BASE" | tee -a $LOG_FILE
-echo "Release version: $RELEASE_NUMBER" | tee -a $LOG_FILE
-echo "Install on Server Name: `uname -n`" | tee -a $LOG_FILE
-echo "==" | tee -a $LOG_FILE
-
-echo "Running the dependency test" | tee -a $LOG_FILE
-echo "Missing dependencies:" | tee -a $LOG_FILE
-for dependency in $DEPENDENCIES
-do
-    token=`which $dependency`
-    if [ ! -f "$token" ]
-    then
-       echo "Dependency: $dependency" | tee -a $LOG_FILE
-       rstatus="Failed"
-    fi
-done
-# Check Lib dependency
-for dependency in $LIB_DEPENDENCIES
-do
-  tokens=`locate $dependency`
-  for lib_path in $tokens
-  do
-    if [ ! -f $lib_path ]
-    then
-      echo "Dependency: $dependency" | tee -a $LOG_FILE
-      rstatus="Failed"
-    fi
-  done
-done
-
-echo "==" | tee -a $LOG_FILE
-if [ "$rstatus" == Failed ]
-then
-  echo "Dependency test Failed" | tee -a $LOG_FILE
-  exit 1
-fi
-echo "Dependency test passed" | tee -a $LOG_FILE
-
-# Execute the Install command for this package
-if [ ! -d $PACKAGE_BASE ]
-then
-   echo "Path to $GIT_REPOS install directory not correct. See $PACKAGE_BASE" | tee -a $LOG_FILE
-   exit 1
-fi
-
 cd $PACKAGE_BASE
-rstatus="SUCCESS"
 #
 #update path to binaries to /opt/software/bin
-./bootstrap.sh --prefix=$SOFTWARE_BASE  2>&1 | tee -a $LOG_FILE
+./bootstrap.sh --prefix=$SOFTWARE_BASE  2>&1
 #Check the install
 if [ $? -ne 0 ]; then
       echo
@@ -118,14 +44,19 @@ if [ $? -ne 0 ]; then
       echo "Consult $LOG_FILE for more details"
       exit 1
 fi
-./bjam --prefix=$SOFTWARE_BASE link=static runtime-link=static stage install 2>&1 | tee -a $LOG_FILE 
+./bjam --prefix=$SOFTWARE_BASE link=static runtime-link=static stage install 2>&1 
 if [ $? -ne 0 ]; then
-      echo
-      echo "'./bjam --prefix=$SOFTWARE_BASE link=static runtime-link=static stage install' Failed." 
+      echo ""
+      echo "'./bjam --prefix=${SOFTWARE_BASE} link=static runtime-link=static stage install' Failed." 
       echo "Consult $LOG_FILE for more details"
       exit 1
 fi
-cd $SOFTWARE_BASE/include/boost
+BOOST_DIR=${SOFTWARE_BASE}/include/boost
+if [ ! -d ${BOOST_DIR} ]; then
+   echo "Install failed: missing directory - ${BOOST_DIR}"
+   exit 1
+fi
+cd ${BOOST_DIR}
 mkdir tr1
 cp *.hpp tr1
 
