Update Install

diff --git a/R/Install b/R/Install
--- a/R/Install
+++ b/R/Install
@@ -10,42 +10,36 @@
 # 3) builds and install R
 #
 # Note: the following environment variables are expected to be set
-#       by the caller
+# by the caller
 # 1) GLOBAL_CONFIG
-# 2) RELEASE_NUMBER
+# 2) PACKAGE_BASE
 #
 cd `dirname $0`
 SCRIPT_NAME=`basename $0`
 WORKING_DIR=`pwd`
 TAR=`which tar`
-
+echo "==" 
+echo "Server Name: `uname -n`" 
+echo "Install Date: `date`" 
 if [ ! -f ../${GLOBAL_CONFIG} ]
 then
   echo "'../${GLOBAL_CONFIG}' file missing "     
   exit 1
 fi
 source ./../${GLOBAL_CONFIG}
-PACKAGE_CONFIG_FILE=R${PACKAGE_CONFIGFILE_SUFFIX}
-source ./${PACKAGE_CONFIG_FILE}
-
-PACKAGE_BASE=${EXTERNAL_SOFTWARE_BASE}/${SHORT_NAME}
-if [ ! -d ${PACKAGE_BASE}/${RELEASE_DIR} ]
+if [ ! -f ${PACKAGE_DEPENDENCIES_FILE} ]
 then
-   echo "ERROR: Missing the install directory ${PACKAGE_BASE}/${RELEASE_DIR} "
+   echo "ERROR: ${PACKAGE_DEPENDENCIES_FILE} file missing"
    exit 1
 fi
-LOG_FILE="${DOWNLOADS_LOG_DIR}/${SCRIPT_NAME}.${SHORT_NAME}.${RELEASE_NUMBER}.log"
-
-rm -rf ${LOG_FILE}
-touch ${LOG_FILE}
-rstatus=""
-echo "==" | tee -a ${LOG_FILE}
-echo "Product: ${SHORT_NAME}" | tee -a ${LOG_FILE}
-echo "Install directory: ${PACKAGE_BASE}" | tee -a ${LOG_FILE}
-echo "Release version: ${RELEASE_NUMBER}" | tee -a ${LOG_FILE}
-echo "Install on Server Name: `uname -n`" | tee -a ${LOG_FILE}
-echo "==" | tee -a ${LOG_FILE}
-cd ${PACKAGE_BASE}/${RELEASE_DIR}
+source ./${PACKAGE_DEPENDENCIES_FILE}
+if [ ! -d ${PACKAGE_BASE} ]
+then
+   echo "ERROR: Missing the install directory ${PACKAGE_BASE} "
+   exit 1
+fi
+RELEASE_DIR=`basename ${PACKAGE_BASE}`
+cd ${PACKAGE_BASE}
 #
 # as defined in the package config file
 if [ ! -f ${REMOTE_FILES} ]
@@ -53,8 +47,8 @@ then
    echo "ERROR - tar file:${REMOTE_FILES} missing under `pwd`"
    exit 1 
 fi
-echo "Running ${TAR} -xvf ${REMOTE_FILES} command from "`pwd` | tee -a ${LOG_FILE}
-${TAR} -xvf ${REMOTE_FILES} 2>&1 | tee -a $LOG_FILE
+echo "Running ${TAR} -xvf ${REMOTE_FILES} command from "`pwd` 
+${TAR} -xvf ${REMOTE_FILES} 2>&1 
 if [ ! -d ${RELEASE_DIR} ]
 then
    rstatus="FAILED"
@@ -65,12 +59,11 @@ mv ${RELEASE_DIR}/* .
 rm -rf ${RELEASE_DIR}/
 #cleanup the tar file
 rm -f $REMOTE_FILES
-echo "Running the install from "`pwd` | tee -a $LOG_FILE
+echo "Running the install from "`pwd` 
 ./configure --prefix=$SOFTWARE_BASE --with-x=no
 make
 make install
 
-echo "Install Done" | tee -a $LOG_FILE
 #make install-info
 #make install-pdf
 exit 0
